controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

controllers_rest:
    resource: ../src/Controller/Api/
    type:     annotation
    prefix:   '/api/v1'
    trailing_slash_on_root: false